language: java
jdk:
  - openjdk8
script:
  - ./gradlew build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: web/build/deploy-me
  on:
    branch: master
after_success:
  - bash <(curl -s https://codecov.io/bash)
